# Generated by Django 4.1.3 on 2022-12-01 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('open_seats', models.PositiveIntegerField(default=30)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_registration.instructor')),
            ],
        ),
    ]
